include:
  - ./docker-compose.yaml

services:

    backend:
      build:
        context: ./backend
        dockerfile: ./Dockerfile
        args:
          - BUILD=prod
      depends_on:
        database:
          condition: service_healthy

    frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
        args:
          - BUILD=prod
