include:
  - ../docker-compose.yaml

services:

    backend:
        build:
            context: ../backend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        environment:
            DB_VERSION: ${DB_VERSION}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        volumes:
            - ..:/workspace

    frontend:
        build:
            context: ../frontend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        volumes:
            - ..:/workspace
