services:

    backend:
        build:
            context: ../backend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        networks:
            - local_network
        volumes:
            - ..:/workspace

    frontend:
        build:
            context: ../frontend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        networks:
            - local_network
        volumes:
            - ..:/workspace

networks:
    local_network: