include:
  - ../docker-compose.yaml

services:

    backend:
        build:
            context: ../backend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
            environment:
                DATABASE_URL: ${DATABASE_URL}
                DB_VERSION:   ${DB_VERSION}
        volumes:
            - ..:/workspace

    frontend:
        build:
            context: ../frontend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        volumes:
            - ..:/workspace
