include:
  - ../docker-compose.yaml

services:

    backend:
        build:
            context: ../backend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        env_file: ../.env
        volumes:
            - ..:/workspace

    frontend:
        build:
            context: ../frontend
            dockerfile: ./Dockerfile
            args:
                - BUILD=dev
        env_file: ../.env
        volumes:
            - ..:/workspace
